# Generated by Django 3.2.5 on 2024-04-11 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dwitter', '0003_auto_20240410_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
    ]
