# Generated by Django 3.2.5 on 2024-05-10 10:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dwitter', '0004_alter_profile_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='dweet',
            name='post',
            field=models.ImageField(blank=True, null=True, upload_to='post/'),
        ),
        migrations.CreateModel(
            name='comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.CharField(max_length=140)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dweet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='dwitter.dweet')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='comments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
