# Generated by Django 3.2.5 on 2024-05-11 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dwitter', '0005_auto_20240510_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dweet',
            name='post',
            field=models.ImageField(blank=True, null=True, upload_to='static/post/'),
        ),
    ]
