# Generated by Django 3.2.5 on 2024-05-12 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dwitter', '0006_alter_dweet_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='dweet',
            name='title',
            field=models.CharField(default='Title', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dweet',
            name='body',
            field=models.CharField(max_length=500),
        ),
    ]
