# Generated by Django 3.2.5 on 2024-05-12 13:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dwitter', '0008_dweet_likecount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dweet',
            name='likecount',
        ),
        migrations.AddField(
            model_name='dweet',
            name='likedby',
            field=models.ManyToManyField(blank=True, related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
