# Generated by Django 3.2.5 on 2024-05-13 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dwitter', '0009_auto_20240512_1925'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='static/profile_pic/userprofilepic/'),
        ),
    ]
